### ISSUE TITLE
Feature Request - load icons locally

### ISSUE THREAD

**Issue by shaal** [phase2/outline#247]
With the upcoming changes in https://github.com/phase2/outline/pull/245, icons no longer take space in `outline.js` and instead, are loaded on-demand from a CDN.

This feature request is to add a build step in Outline, that scan all elements for specific icons used, and copy these icons to `dist/` directory (`dist/library_name/icon_name`).
The `outline-icon` component should try first load icons locally and if not found, load from CDN as fallback.

This would result in better performance (loading from the main website, without waiting for additional CDNs)

**Comment by himerus** [comment]
I believe this can be resolved in 1 of 2 ways. Using the custom resolvers adapted from the Shoelace icon implementation, we should be able to handle this valid concern as below:

### Custom Resolver similar to `library.system.ts`. 

- [library.system.ts](https://github.com/phase2/outline/blob/next/src/components/base/outline-icon/libraries/library.system.ts)
- This would allow a new controller to be added, and svg code is directly applied in the resolver. 

### Custom Resolver similar to `library.custom.ts`. 

- [library.custom.ts](https://github.com/phase2/outline/blob/next/src/components/base/outline-icon/libraries/library.custom.ts)
- This would allow any icon svgs added to `src/assets/svg/custom/` to be available to the system locally. 
  - Icons from `src/assets/svg/custom/` will be copied to 

Since MOST project implementations use under 50 icons? 20 icons? I think either of these methods would be a safe way to execute a more performant set than always relying on CDN. 

Please let me know if you think this does not solve the issue in question.

**Comment by himerus** [comment]
Closing this as unnecessary. Solution described above.
